# Generated by Django 5.2.8 on 2025-11-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Salão')),
                ('subdominio', models.CharField(help_text='Identificador único na URL (ex: salao1)', max_length=100, unique=True, verbose_name='Subdomínio')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salão',
                'verbose_name_plural': 'Salões',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='salao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.salao', verbose_name='Salão'),
        ),
    ]
