# Generated by Django 5.2.8 on 2025-11-26 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('cabelo', 'Cabelo'), ('pele', 'Pele'), ('unhas', 'Unhas')], max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(default='bi-scissors', max_length=50, verbose_name='Ícone (Bootstrap Icons)')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia')),
                ('especialidades', models.CharField(blank=True, max_length=500, verbose_name='Especialidades')),
                ('horario_inicio', models.TimeField(default='09:00', verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(default='18:00', verbose_name='Horário de Fim')),
                ('trabalha_segunda', models.BooleanField(default=True, verbose_name='Segunda-feira')),
                ('trabalha_terca', models.BooleanField(default=True, verbose_name='Terça-feira')),
                ('trabalha_quarta', models.BooleanField(default=True, verbose_name='Quarta-feira')),
                ('trabalha_quinta', models.BooleanField(default=True, verbose_name='Quinta-feira')),
                ('trabalha_sexta', models.BooleanField(default=True, verbose_name='Sexta-feira')),
                ('trabalha_sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('trabalha_domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('modulos', models.ManyToManyField(related_name='profissionais', to='servicos.modulo', verbose_name='Módulos que Atende')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profissional', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('duracao_minutos', models.IntegerField(default=60, verbose_name='Duração (minutos)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='servicos.modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['modulo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='servicos.profissional', verbose_name='Profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='servicos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data', '-hora'],
                'unique_together': {('profissional', 'data', 'hora')},
            },
        ),
    ]
