# Generated by Django 5.2.8 on 2025-11-27 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salao_usuario_salao'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='salao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.salao', verbose_name='Salão'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='salao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='core.salao', verbose_name='Salão'),
        ),
        migrations.AddField(
            model_name='servico',
            name='salao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.salao', verbose_name='Salão'),
        ),
    ]
