# Generated by Django 5.2.8 on 2025-11-26 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Material')),
                ('modulo', models.CharField(choices=[('cabelo', 'Cabelo'), ('pele', 'Pele'), ('unhas', 'Unhas'), ('geral', 'Geral')], max_length=20, verbose_name='Módulo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade em Estoque')),
                ('unidade', models.CharField(default='unidade', max_length=20, verbose_name='Unidade')),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Unitário')),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Estoque Mínimo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['modulo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('motivo', models.CharField(blank=True, max_length=500, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='gestao.material', verbose_name='Material')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=20, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('servico', 'Serviço Prestado'), ('fornecedor', 'Fornecedor'), ('salario', 'Salário'), ('aluguel', 'Aluguel'), ('conta', 'Conta (Água, Luz, etc)'), ('outro', 'Outro')], max_length=30, verbose_name='Categoria')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago/Recebido')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='servicos.agendamento', verbose_name='Agendamento Relacionado')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='servicos.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
